"""Fleet overview, aircraft list and aircraft health detail."""
from __future__ import annotations

import numpy as np
from fastapi import APIRouter, HTTPException

from ...config import FH_PER_CYCLE
from ...domain.catalog import AIRCRAFT_TYPES, ATA_CHAPTERS, BASES, LRU_TYPES, SQUADRONS
from ...domain.environment import base_table
from ...prognostics.engine_rul import hums_window
from ...twin.state import CHECKS, ENGINE_IDX, LRU_IDS, SQN_IDS, STATE_LABELS, STATE_NAMES, TYPE_IDS
from ..context import get_ctx

router = APIRouter(prefix="/api", tags=["fleet"])


@router.get("/meta")
def meta():
    ctx = get_ctx()
    return {
        "today": ctx.today, "day": ctx.state.day,
        "squadrons": [{"id": s.id, "name": s.name, "base": s.base, "type": s.type, "n": s.n_aircraft, "bays": s.bays}
                      for s in SQUADRONS.values()],
        "bases": [{"id": b.id, "name": b.name, "lat": b.lat, "lon": b.lon, "climate": b.climate} for b in BASES.values()],
        "types": {k: {"label": t.label, "engines": t.engines, "checks": [c.__dict__ for c in t.checks]}
                  for k, t in AIRCRAFT_TYPES.items()},
        "states": STATE_LABELS, "ata": ATA_CHAPTERS,
        "lrus": [{"id": l.id, "name": l.name, "ata": l.ata, "system": l.system, "cost_lakh": l.cost_lakh,
                  "source": l.source, "agency": l.agency} for l in LRU_TYPES.values()],
        "provenance": "Notional fleet generated by the TATPAR Fleet Twin; engine health from NASA C-MAPSS; "
                      "dust from CAMS 2024. Not IAF data.",
    }


def _tail_rows(ctx):
    st = ctx.state
    status = st.status()
    rows = []
    rogue = set(ctx.tables["rogue_units"].query("flag")["serial"]) if len(ctx.tables["rogue_units"]) else set()
    chronic = set(ctx.tables["chronic_defects"]["tail"]) if len(ctx.tables["chronic_defects"]) else set()
    for t, tail in enumerate(st.tail_ids):
        ty = AIRCRAFT_TYPES[TYPE_IDS[st.tail_type[t]]]
        pos = st.positions_of(t)
        r7 = ctx.risk7[pos]
        eng = [p for p in pos if st.pos_type[p] == ENGINE_IDX and st.pos_serial[p] >= 0]
        eng_rul = []
        for p in eng:
            lo, med, hi = ctx.belief.engine_quantiles(st, int(st.pos_serial[p]))
            eng_rul.append(med * FH_PER_CYCLE)
        p_any7 = float(1 - np.prod(1 - r7))
        rows.append({
            "tail": tail, "squadron": SQN_IDS[st.tail_sqn[t]], "base": SQUADRONS[SQN_IDS[st.tail_sqn[t]]].base,
            "type": ty.id, "state": STATE_NAMES[status[t]], "hours_total": round(float(st.hrs_total[t]), 1),
            **{f"to_{c}": round(float(ty.check(c).interval_fh - st.hrs_since[c][t]), 1) for c in CHECKS},
            "check": st.check_kind[t] or None, "missing_parts": int(st.missing[t]),
            "p_snag_7d": round(p_any7, 3), "engine_rul_fh_min": round(min(eng_rul), 0) if eng_rul else None,
            "rogue_parts": int(sum(int(st.pos_serial[p]) in rogue for p in pos)), "chronic": tail in chronic,
        })
    return rows


@router.get("/fleet")
def fleet():
    return _tail_rows(get_ctx())


@router.get("/overview")
def overview():
    ctx = get_ctx()
    st = ctx.state
    status = st.status()
    fc = ctx.bench("forecast") or {}
    rows = _tail_rows(ctx)
    sq = []
    for k, q in enumerate(SQN_IDS):
        m = st.tail_sqn == k
        b = fc.get("baseline", {}).get("squadrons", {}).get(q, {})
        t = fc.get("tatpar", {}).get("squadrons", {}).get(q, {})
        sq.append({"id": q, "name": SQUADRONS[q].name, "base": SQUADRONS[q].base, "n": int(m.sum()),
                   "mc_now": int((status[m] == 0).sum()),
                   "states": {STATE_NAMES[s]: int((status[m] == s).sum()) for s in range(len(STATE_NAMES))},
                   "d7_baseline": [b.get("p10", [None] * 8)[7], b.get("p50", [None] * 8)[7], b.get("p90", [None] * 8)[7]] if b else None,
                   "d30_baseline": [b["p10"][30], b["p50"][30], b["p90"][30]] if b else None,
                   "d30_tatpar": [t["p10"][30], t["p50"][30], t["p90"][30]] if t else None})
    risks = sorted(rows, key=lambda r: -r["p_snag_7d"])[:8]
    eng = sorted([r for r in rows if r["engine_rul_fh_min"] is not None], key=lambda r: r["engine_rul_fh_min"])[:5]
    adv = ctx.bench("advisors") or {}
    lev = ctx.bench("levers") or {}
    return {
        "today": ctx.today, "n_tails": st.n_tails, "mc_now": int((status == 0).sum()),
        "states": {STATE_NAMES[s]: int((status == s).sum()) for s in range(len(STATE_NAMES))},
        "squadrons": sq, "top_risks": risks, "engine_watch": eng,
        "forecast": {"baseline": fc.get("baseline", {}).get("fleet"), "tatpar": fc.get("tatpar", {}).get("fleet"),
                     "calibration": fc.get("calibration")},
        "actions": {"transfers": len(adv.get("transfers", [])), "aog": len(adv.get("cannibalisation", [])),
                    "expedite": len(adv.get("expedite", []))},
        "headline": {"baseline_mc": lev.get("rows", [{}])[0].get("mc"), "tatpar_mc": lev.get("rows", [{}])[-1].get("mc"),
                     "delta": lev.get("total_delta"), "ci": lev.get("total_ci"), "aircraft": lev.get("aircraft_equivalent")},
        "environment": base_table(),
    }


@router.get("/aircraft/{tail}")
def aircraft(tail: str):
    ctx = get_ctx()
    st = ctx.state
    if tail not in st.tail_ids:
        raise HTTPException(404, "unknown tail")
    t = st.tail_ids.index(tail)
    row = next(r for r in _tail_rows(ctx) if r["tail"] == tail)
    pos = st.positions_of(t)
    lrus = []
    for p in pos:
        li = int(st.pos_type[p])
        ser = int(st.pos_serial[p])
        l = LRU_TYPES[LRU_IDS[li]]
        lrus.append({"pos": int(p), "lru": l.id, "name": l.name, "ata": l.ata, "system": l.system,
                     "serial": ser if ser >= 0 else None, "hours_since_repair": round(float(st.ser_hrs[ser]), 1) if ser >= 0 else None,
                     "p_fail_7d": round(float(ctx.risk7[p]), 4), "p_fail_30d": round(float(ctx.risk30[p]), 4),
                     "missing": ser < 0})
    engines = []
    eng_tab = ctx.tables["engines"].set_index("pos") if len(ctx.tables["engines"]) else None
    for p in pos:
        if st.pos_type[p] != ENGINE_IDX or st.pos_serial[p] < 0:
            continue
        ser = int(st.pos_serial[p])
        uid = st.engine_units[int(st.ser_unit[ser])]
        cyc = int(min(st.engine_unit_life[int(st.ser_unit[ser])] - 1, max(2, st.ser_age[ser] // FH_PER_CYCLE)))
        win = hums_window(uid, cyc)
        pred = ctx.rul.predict_features(ctx.rul.featurize(win))
        step = max(1, len(pred) // 60)
        trend = [{"cycle": int(c), "lo": float(a), "med": float(b), "hi": float(d)}
                 for c, a, b, d in zip(win["cycle"].to_numpy()[::step], pred["rul_lo"].to_numpy()[::step],
                                       pred["rul_med"].to_numpy()[::step], pred["rul_hi"].to_numpy()[::step])]
        last = pred.iloc[-1]
        sensors = {s: [float(v) for v in win[s].to_numpy()[-60:]] for s in ("T30", "T50", "Ps30", "phi")}
        engines.append({
            "pos": int(p), "serial": ser, "hums_source": f"NASA C-MAPSS {uid}", "cycle": cyc,
            "rul_cycles": {"lo": float(last["rul_lo"]), "med": float(last["rul_med"]), "hi": float(last["rul_hi"])},
            "rul_fh": {"lo": float(last["rul_lo"] * FH_PER_CYCLE), "med": float(last["rul_med"] * FH_PER_CYCLE),
                       "hi": float(last["rul_hi"] * FH_PER_CYCLE)},
            "modules": ctx.rul.explain(win), "trend": trend, "sensors": sensors,
        })
    sn = ctx.tables["snags"]
    sn = sn[sn["tail"] == tail].sort_values("day", ascending=False).head(25)
    chronic = ctx.tables["chronic_defects"]
    return {
        **row, "type_label": AIRCRAFT_TYPES[row["type"]].label,
        "lrus": lrus, "engines": engines,
        "snags": sn[["snag_id", "date", "ata", "system", "lru", "text", "action", "finding"]].astype({"date": str}).to_dict("records"),
        "chronic": chronic[chronic["tail"] == tail].to_dict("records") if len(chronic) else [],
        "ata_names": ATA_CHAPTERS,
    }
